name: Lint

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"
      - "package.json"
  workflow_dispatch:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - uses: bahmutov/npm-install@v1
      - name: lint - ESLint
        run: yarn run lint:eslint

  prettier:
    name: prettier
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: bahmutov/npm-install@v1
      - name: lint - Prettier
        run: yarn run lint:prettier

  transpile:
    name: transpile
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: bahmutov/npm-install@v1
      - name: tsc - noEmit
        run: yarn run tsc --noEmit
