name: Lint

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - uses: bahmutov/npm-install@v1
      - name: lint - ESLint
        run: yarn run lint:eslint

  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: bahmutov/npm-install@v1
      - name: lint - Prettier
        run: yarn run lint:prettier
