name: Lint

on:
  push:
    branches:
      - master
      - dev
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"
      - "package.json"
  workflow_dispatch:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - uses: bahmutov/npm-install@v1

      - name: lint - ESLint
        run: yarn run lint

  transpile:
    name: transpile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - uses: bahmutov/npm-install@v1

      - name: tsc - noEmit
        run: yarn run typecheck
