name: storybook

on:
  push:
    branches:
      - master
    paths:
      - "src/**/*.stories.tsx"
  workflow_dispatch:

jobs:
  deploy-storybook:
    name: storybook
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn

      - uses: bahmutov/npm-install@v1

      - name: build-storybook
        run: yarn run build-storybook

      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: storybook
